- O formato das Sequências de proteínas deve ser especificado em `DATA_FORMATT`

In [1131]:
# !pip install -r ../requirements.txt

In [1132]:
from Bio import Phylo
from Bio import *
from dendropy import Tree
import shutil, os, hashlib, pickle, sys
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpmax, fpgrowth
import hashlib, json


INPUT_PATH = '../data/out/Trees'
DATA_OUTPUT_PATH = '../data/out'
DATA_OUTPUT_PATH_SUBTREE = os.path.join(DATA_OUTPUT_PATH,'Subtrees')
OUTPUT_JSON = os.path.join(DATA_OUTPUT_PATH,'output.json')
OUTPUT_LOG = os.path.join(DATA_OUTPUT_PATH,'output_log.txt')

DATA_FORMAT = 'nexus' # newick ou nexus
match DATA_FORMAT:
    case 'nexus':
        EXTENTION_FORMAT = 'nexus' # Nexus: 'nexus'
   
    case 'nwk':
        EXTENTION_FORMAT = 'nwk' # Newick: 'nwk'

# Redirecione a saída padrão para o arquivo "output_log.txt"
sys.stdout = open(OUTPUT_LOG, "w")

<h3 align="center"> <b>Limpeza</b> </h3>

In [1133]:
def clean_dir(path_clean):
    if(os.path.exists(path_clean)):
        for name in os.listdir(path_clean):
            if(name != "file.gitkeep"):
                file_path = os.path.join(path_clean, name)
                os.remove(file_path)
        shutil.rmtree(path_clean)

def clean_files():
    dir_tmp = os.path.join(DATA_OUTPUT_PATH_SUBTREE) 
    arquivos_tmp = os.listdir(dir_tmp)
    for name_file in arquivos_tmp:
        if name_file != "file.gitkeep":
            os.remove(os.path.join(dir_tmp,name_file))

clean_files()

<h3 align="center"> <b>Exibe subárvore</b> </h3>

In [1134]:
def print_trees_in_directory(directory):
    for filename in os.listdir(directory):
        if filename.endswith(f'.{EXTENTION_FORMAT}'):
            filepath = os.path.join(directory, filename)
            
            print(filename.upper() + "\n")
            tree = Tree.get_from_path(filepath, DATA_FORMAT)
            tree.print_plot()


<h3 align="center"> <b>Construtor de subárvores</b> </h3>

In [1135]:
def calculate_tree_hash(data):
    newick = data.format("newick")
    hash_object = hashlib.md5(newick.encode())
    return {
        'newick': newick,
        'terrminal_hash': int(hash_object.hexdigest()[:2], 16)
    }

def decode_tree_hash(encoded_data):
    newick = encoded_data['newick']
    original_hash = encoded_data['terrminal_hash']
    hash_object = hashlib.md5(newick.encode())
    if int(hash_object.hexdigest()[:2], 16) == original_hash:
        return newick
    else:
        return None

In [1136]:

def encode_list_to_int(lst):
    lst_str = ",".join(map(str, lst))
    hash_object = hashlib.md5(lst_str.encode())
    return {
            'list':lst,
            'encode_list':int(hash_object.hexdigest()[:2], 16)
        }

def decode_int_to_list(encoded_data):
    lst = ",".join(map(str, encoded_data['list']))
    original_hash = encoded_data['encode_list']
    hash_object = hashlib.md5(str(lst).encode())
    if int(hash_object.hexdigest()[:2], 16) == original_hash:
        return encoded_data['list']
    else:
        return None

In [1137]:
def sub_tree(path, name_tree):
    tree = Phylo.read(path, DATA_FORMAT)
    name_tree = name_tree.rsplit(".", 1)[0]
    
    
    print('='*100)
    
    tree_hash = calculate_tree_hash(tree)['terrminal_hash']
    print(f'\nTREE: HASH VALUE\n{name_tree}: {tree_hash}\n')
    
    # Lista caminhos das subárvores (que posteriormente serão utilizadas para compor a matriz de subárvores)
    dict_tree_terminals_hash = {}
    dict_aux = {}
    result_dict = {}

    for clade in tree.find_clades():
        hash_list = []
        subtree_list_termials = []
        
        subtree = Phylo.BaseTree.Tree(clade)
        name_subtree = f'{name_tree}_{clade.name}'

        if(clade.is_terminal()):
            clade_hash = calculate_tree_hash(clade.name)['terrminal_hash']
            dict_tree_terminals_hash[clade.name] = clade_hash
            
        if subtree.count_terminals() > 1:
            print(f'\nSUBTREE:\n{name_subtree}\n')
            Phylo.draw_ascii(subtree)
            print('\n')

            filepath_out = os.path.join(DATA_OUTPUT_PATH_SUBTREE, f'{name_tree}_{clade.name}.{EXTENTION_FORMAT}')
            Phylo.write(subtree, filepath_out, DATA_FORMAT)
                           
            for subtree_clade in subtree.find_clades():
                name_terminal = subtree_clade.name
                if(subtree_clade.is_terminal()):

                    hash_result = calculate_tree_hash(name_terminal)
                    hash_list.append(hash_result)
                
                    subtree_list_termials.append(hash_result['terrminal_hash'])
                    
                    print(f'subtree clade: {subtree_clade}: {hash_result["terrminal_hash"]}')
                    print(f'Decode: {decode_tree_hash(hash_result)}')

            dict_aux[name_subtree] = {'Terminals':subtree_list_termials,'List_terminals_hash':encode_list_to_int(subtree_list_termials),'data_terminals':hash_list}
            print(f'\nTerminais: {subtree_list_termials}:{encode_list_to_int(subtree_list_termials)}\n')

    result_dict[name_tree] = dict_aux
    print(f'CLADES DA ARVORE {name_tree}:\n')       
    for key, value in dict_tree_terminals_hash.items():
        print(f'{key}: {value}') 
    print('-'*100)
 
    return result_dict

<h3 align="center"> <b>Chamada de funções</b> </h3>

<p align="center"> <b> ATENÇÃO: SE A ÁRVORE DE ENTRADA NÃO TIVER FORMATO NEXUS, MUDAR O SCHEMA EM Phylo.write( )
</b> </p>

In [1138]:
# Diretório de entrada de árvores 
arquivos = os.listdir(INPUT_PATH)

# matriz com todas as subárvores
dados_brutos = []
matriz_subtree_data = []
matriz_subtree_hashs = []

for name_file in arquivos:
    if(name_file != "file.gitkeep"):
        dir_path_out_epsecif = os.path.join(DATA_OUTPUT_PATH_SUBTREE,name_file.split(".")[0])
        file_path = os.path.join(INPUT_PATH,name_file)
        dados_brutos.append(sub_tree(file_path, name_file))

In [1139]:
json_result = json.dumps(dados_brutos, indent=2)
with open(OUTPUT_JSON, 'w') as output_file:
    output_file.write(json_result)

In [1140]:
def extract_terminais_list(data):
    all_terminais = []
    for _, tree_info in data.items():
        for _, subtree_info in tree_info.items():
            all_terminais.append(subtree_info['Terminals'])
    return all_terminais

for metadata in dados_brutos:
    subtree_by_line = []
    for termianls in extract_terminais_list(metadata):
        terminals_encoded = encode_list_to_int(termianls)
        # print(f'Enconded List: {terminals_encoded}')
        # print(f'Decoded List: {decode_int_to_list(terminals_encoded)}')
        matriz_subtree_data.append(terminals_encoded)
        subtree_by_line.append(terminals_encoded['encode_list'])
    matriz_subtree_hashs.append(subtree_by_line)

In [1141]:
print(f'\nHASH KEY ARRAY BEFORE NORMALIZING\n')

for linha in matriz_subtree_hashs:
    print(linha)

In [1142]:
max_columns = max(len(row) for row in matriz_subtree_hashs)
# máximo de linhas
max_rows = len(matriz_subtree_hashs)

def preencher_matriz(matriz, valor_preenchimento):
    # Preencher as células vazias com o valor de preenchimento
    for row in matriz:
        while len(row) < max_columns:
            row.append(valor_preenchimento)

    return matriz

print(f'\nDIM: {max_rows}x{max_columns} ','-'*20)


- [FPmax - python](https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/fpmax/)

In [1143]:
te = TransactionEncoder()
te_ary = te.fit(matriz_subtree_hashs).transform(matriz_subtree_hashs)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,7,13,14,16,17,28,29,32,36,40,...,196,209,215,218,222,229,240,241,245,250
0,False,False,False,True,False,True,False,False,False,False,...,False,False,False,False,True,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,True,False,False,True,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,True,...,False,False,False,False,False,False,False,True,False,False
5,False,True,False,True,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,True,False
6,False,False,False,False,False,False,False,False,True,False,...,False,True,True,False,False,False,False,False,False,True
7,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [1144]:
result_fpmax = fpmax(df, min_support=0.2, use_colnames=True)
# print(dict(result_fpmax))
result_fpmax

   support itemsets
0     0.25     (16)
1     0.25     (36)
2     0.25     (41)

In [1151]:
def finds_frequent_subtrees(metadata, fpmax_result):
    for _, line_fpmax in fpmax_result.iterrows():
        print(line_fpmax['itemsets'])

In [1155]:
finds_frequent_subtrees(dados_brutos, result_fpmax)

/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

In [1145]:
fpgrowth(df, min_support=0.2, use_colnames=True)

   support itemsets
0     0.25     (41)
1     0.25     (16)
2     0.25     (36)

In [1146]:
# # matriz_subtree = preencher_matriz(matriz_subtree, None)
matriz_subtree = preencher_matriz(matriz_subtree_hashs, -1)

print(f'\nHASH KEY ARRAY AFTER NORMALIZING\n')

for linha in matriz_subtree:
    print(linha)

In [1147]:
# !pip install --upgrade pandas numpy
# import warnings
# warnings.filterwarnings("ignore", category=DeprecationWarning)

In [1148]:
def find_exact_subsets(subtree_data, result_fpmax):
    subconjuntos_exatos = {}

    for key, conjunto in subtree_data.items():
        conjunto_frozen = conjunto

        for _, linha_fpmax in result_fpmax.iterrows():
            if conjunto_frozen in linha_fpmax['itemsets']:
                subconjuntos_exatos[key] = conjunto
                break
    print("\n\n\nSubárvores com subconjuntos exatos de result_fpmax:\n")
    
    for key, value in subconjuntos_exatos.items():
        print(f'{key}:{value}')

find_exact_subsets(subtree_data, result_fpmax)

<h3 align="center"> <b> Comparação das subárvores
</b> </h3>