- O formato das Sequências de proteínas deve ser especificado em `DATA_FORMATT`

In [1022]:
# !pip install -r ../requirements.txt

In [1023]:
from Bio import Phylo
from Bio import *
from dendropy import Tree
import shutil, os, hashlib, pickle, sys
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpmax, fpgrowth
import hashlib


INPUT_PATH = '../data/out/Trees'
DATA_OUTPUT_PATH = '../data/out/Subtrees'

DATA_FORMAT = 'nexus' # newick ou nexus
match DATA_FORMAT:
    case 'nexus':
        EXTENTION_FORMAT = 'nexus' # Nexus: 'nexus'
   
    case 'nwk':
        EXTENTION_FORMAT = 'nwk' # Newick: 'nwk'

# Redirecione a saída padrão para o arquivo "output_log.txt"
sys.stdout = open("output_log.txt", "w")

<h3 align="center"> <b>Limpeza</b> </h3>

In [1024]:
def clean_dir(path_clean):
    if(os.path.exists(path_clean)):
        for name in os.listdir(path_clean):
            if(name != "file.gitkeep"):
                file_path = os.path.join(path_clean, name)
                os.remove(file_path)
        shutil.rmtree(path_clean)

def clean_files():
    dir_tmp = os.path.join(DATA_OUTPUT_PATH) 
    arquivos_tmp = os.listdir(dir_tmp)
    for name_file in arquivos_tmp:
        if name_file != "file.gitkeep":
            os.remove(os.path.join(dir_tmp,name_file))

clean_files()

<h3 align="center"> <b>Exibe subárvore</b> </h3>

In [1025]:
def print_trees_in_directory(directory):
    for filename in os.listdir(directory):
        if filename.endswith(f'.{EXTENTION_FORMAT}'):
            filepath = os.path.join(directory, filename)
            
            print(filename.upper() + "\n")
            tree = Tree.get_from_path(filepath, DATA_FORMAT)
            tree.print_plot()


<h3 align="center"> <b>Construtor de subárvores</b> </h3>

In [1026]:
def calculate_tree_hash(data):
    newick = data.format("newick")
    hash_object = hashlib.md5(newick.encode())
    return {
        'newick': newick,
        'hash': int(hash_object.hexdigest()[:2], 16)
    }

def decode_tree_hash(encoded_data):
    newick = encoded_data['newick']
    original_hash = encoded_data['hash']
    hash_object = hashlib.md5(newick.encode())
    if int(hash_object.hexdigest()[:2], 16) == original_hash:
        return newick
    else:
        return None

In [1027]:

def encode_list_to_int(lst):
    lst_str = ",".join(map(str, lst))
    hash_object = hashlib.md5(lst_str.encode())
    return int(hash_object.hexdigest()[:2], 16)

def decode_int_to_list(encoded_int, original_list):
    lst_str = ",".join(map(str, original_list))
    hash_object = hashlib.md5(lst_str.encode())
    if int(hash_object.hexdigest()[:2], 16) == encoded_int:
        return original_list
    else:
        return None

In [1028]:
def sub_tree(path, name_tree):
    tree = Phylo.read(path, DATA_FORMAT)
    name_tree = name_tree.rsplit(".", 1)[0]
    
    
    print('='*100)
    
    tree_hash = calculate_tree_hash(tree)['hash']
    print(f'\nTREE: HASH VALUE\n{name_tree}: {tree_hash}\n')
    
    # Lista caminhos das subárvores (que posteriormente serão utilizadas para compor a matriz de subárvores)
    row_subtree = []
    dict_clade_hash = {}
    result_dict = {}

    for clade in tree.find_clades():
        subtree_terminals_hash = []
        subtree = Phylo.BaseTree.Tree(clade)
        
        if(clade.is_terminal()):
            clade_hash = calculate_tree_hash(clade.name)['hash']
            dict_clade_hash[clade.name] = clade_hash
            
        if subtree.count_terminals() > 1:
            print(f'\nSUBTREE:\n{name_tree}_{clade.name}\n')
            Phylo.draw_ascii(subtree)
            print('\n\n')

            filepath_out = os.path.join(DATA_OUTPUT_PATH, f'{name_tree}_{clade.name}.{EXTENTION_FORMAT}')
            Phylo.write(subtree, filepath_out, DATA_FORMAT)
                 
            
            for subtree_clade in subtree.find_clades():
                if(subtree_clade.is_terminal()):
                    hash_result = calculate_tree_hash(subtree_clade.name)
                    subtree_terminals_hash.append(calculate_tree_hash(subtree_clade.name)['hash'])
                    row_subtree.append(hash_result['hash'])
                    print(f'subtree clade: {subtree_clade}: {hash_result["hash"]}')
                    print(f'Decode: {decode_tree_hash(hash_result)}')
                    
            result_dict[f'{name_tree}_{clade.name}'] = subtree_terminals_hash        
    
    print(f'\nCLADES DA ARVORE {name_tree}:\n')       
    for key, value in dict_clade_hash.items():
        print(f'{key}: {value}')
    print('\n\n')       
    
    print(f'\n\n{row_subtree}\n\n')  
    print('-'*100)

    result_dict[f'row_subtree'] = row_subtree     
    return result_dict

In [1029]:
def directory_has_single_file(directory_path):
    if not os.path.isdir(directory_path):
        return False

    files = os.listdir(directory_path)
    if len(files) != 1:
        return False

    return True

<h3 align="center"> <b>Chamada de funções</b> </h3>

<p align="center"> <b> ATENÇÃO: SE A ÁRVORE DE ENTRADA NÃO TIVER FORMATO NEXUS, MUDAR O SCHEMA EM Phylo.write( )
</b> </p>

In [1030]:
# Diretório de entrada de árvores 
arquivos = os.listdir(INPUT_PATH)

# matriz com todas as subárvores
dados_brutos = []
matriz_subtree = []

for name_file in arquivos:
    if(name_file != "file.gitkeep"):
        dir_path_out_epsecif = os.path.join(DATA_OUTPUT_PATH,name_file.split(".")[0])
        file_path = os.path.join(INPUT_PATH,name_file)
        dados_brutos.append(sub_tree(file_path, name_file))

for data in dados_brutos:
    matriz_subtree.append(data['row_subtree'])

In [1031]:
print(f'DADOS BRUTOS:\n')
subtree_data = {}
for catalog in dados_brutos:
    for key, value in catalog.items():
        # print(f'{key}:{value}')
        if key != 'row_subtree':
            encoded_int = encode_list_to_int(value)
            subtree_data[key] = encoded_int
            
            decoded_list = decode_int_to_list(encoded_int, value)

            print(f"Lista codificada como inteiro: {encoded_int}")
            if decoded_list is not None:
                print(f"Lista decodificada: {decoded_list}")
            else:
                print("Erro na decodificação. O valor inteiro não corresponde à lista original.")

    print()
# print(subtree_data)

In [1032]:
print(f'\nHASH KEY ARRAY BEFORE NORMALIZING\n')

for linha in matriz_subtree:
    print(linha)

In [1033]:
max_columns = max(len(row) for row in matriz_subtree)
# máximo de linhas
max_rows = len(matriz_subtree)

def preencher_matriz(matriz, valor_preenchimento):
    # Preencher as células vazias com o valor de preenchimento
    for row in matriz:
        while len(row) < max_columns:
            row.append(valor_preenchimento)

    return matriz

print(f'\nDIM: {max_rows}x{max_columns} ','-'*20)


- [FPmax - python](https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/fpmax/)

In [1034]:
te = TransactionEncoder()
te_ary = te.fit(matriz_subtree).transform(matriz_subtree)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,3,6,8,10,16,17,21,27,29,33,...,181,186,191,198,212,218,225,226,253,254
0,False,False,False,False,False,False,True,False,False,False,...,True,True,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,True,True,False,False
2,True,False,False,False,False,False,True,False,False,False,...,True,True,False,False,False,True,False,False,False,False
3,True,False,True,False,False,False,True,False,False,False,...,True,False,False,False,True,False,False,False,False,True
4,False,False,False,True,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,True,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
6,False,False,False,False,False,True,False,True,False,True,...,True,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False

In [1035]:
result_fpmax = fpmax(df, min_support=0.2, use_colnames=True)
# print(dict(result_fpmax))
result_fpmax

   support                              itemsets
0     0.25                          (21, 3, 181)
1     0.25                                  (33)
2     0.25  (218, 73, 43, 108, 21, 181, 186, 59)
3     0.25                                 (165)

In [1036]:
fpgrowth(df, min_support=0.2, use_colnames=True)

     support                              itemsets
0      0.500                                 (181)
1      0.375                                  (59)
2      0.375                                  (21)
3      0.250                                 (218)
4      0.250                                 (186)
..       ...                                   ...
256    0.250      (186, 43, 108, 21, 181, 218, 59)
257    0.250  (186, 73, 43, 108, 21, 181, 218, 59)
258    0.250                               (3, 21)
259    0.250                              (3, 181)
260    0.250                          (21, 3, 181)

[261 rows x 2 columns]

In [1037]:
# # matriz_subtree = preencher_matriz(matriz_subtree, None)
matriz_subtree = preencher_matriz(matriz_subtree, -1)

print(f'\nHASH KEY ARRAY AFTER NORMALIZING\n')

for linha in matriz_subtree:
    print(linha)

In [1038]:
# !pip install --upgrade pandas numpy
# import warnings
# warnings.filterwarnings("ignore", category=DeprecationWarning)

In [1039]:
result_fpmax['itemsets'] = result_fpmax['itemsets'].apply(frozenset)

# Identificando subconjuntos exatos em subtree_data
subconjuntos_exatos = {}

for chave, conjunto in subtree_data.items():
    conjunto_frozen = set(conjunto)
    
    for _, linha_fpmax in result_fpmax.iterrows():
        if conjunto_frozen.issubset(linha_fpmax['itemsets']):
            subconjuntos_exatos[chave] = conjunto
            break

print("\n\n\nSubárvores com subconjuntos exatos de result_fpmax:\n")
print(f'\n\n{dict(result_fpmax)}')

for key, value in subconjuntos_exatos.items():
    print(f'{key}:{value}')

TypeError: 'int' object is not iterable

<h3 align="center"> <b> Comparação das subárvores
</b> </h3>