- O formato das Sequências de proteínas deve ser especificado em `DATA_FORMATT`

In [890]:
# !pip install -r ../requirements.txt

In [891]:
from Bio import Phylo
from Bio import *
from dendropy import Tree
import shutil, os, hashlib, pickle, sys
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpmax, fpgrowth
import hashlib, json


INPUT_PATH = '../data/out/Trees'
DATA_OUTPUT_PATH = '../data/out/Subtrees'
OUTPUT_JSON = '../data/out/output.json'

DATA_FORMAT = 'nexus' # newick ou nexus
match DATA_FORMAT:
    case 'nexus':
        EXTENTION_FORMAT = 'nexus' # Nexus: 'nexus'
   
    case 'nwk':
        EXTENTION_FORMAT = 'nwk' # Newick: 'nwk'

# Redirecione a saída padrão para o arquivo "output_log.txt"
sys.stdout = open("output_log.txt", "w")

<h3 align="center"> <b>Limpeza</b> </h3>

In [892]:
def clean_dir(path_clean):
    if(os.path.exists(path_clean)):
        for name in os.listdir(path_clean):
            if(name != "file.gitkeep"):
                file_path = os.path.join(path_clean, name)
                os.remove(file_path)
        shutil.rmtree(path_clean)

def clean_files():
    dir_tmp = os.path.join(DATA_OUTPUT_PATH) 
    arquivos_tmp = os.listdir(dir_tmp)
    for name_file in arquivos_tmp:
        if name_file != "file.gitkeep":
            os.remove(os.path.join(dir_tmp,name_file))

clean_files()

<h3 align="center"> <b>Exibe subárvore</b> </h3>

In [893]:
def print_trees_in_directory(directory):
    for filename in os.listdir(directory):
        if filename.endswith(f'.{EXTENTION_FORMAT}'):
            filepath = os.path.join(directory, filename)
            
            print(filename.upper() + "\n")
            tree = Tree.get_from_path(filepath, DATA_FORMAT)
            tree.print_plot()


<h3 align="center"> <b>Construtor de subárvores</b> </h3>

In [894]:
def calculate_tree_hash(data):
    newick = data.format("newick")
    hash_object = hashlib.md5(newick.encode())
    return {
        'newick': newick,
        'terrminal_hash': int(hash_object.hexdigest()[:2], 16)
    }

def decode_tree_hash(encoded_data):
    newick = encoded_data['newick']
    original_hash = encoded_data['terrminal_hash']
    hash_object = hashlib.md5(newick.encode())
    if int(hash_object.hexdigest()[:2], 16) == original_hash:
        return newick
    else:
        return None

In [895]:

def encode_list_to_int(lst):
    lst_str = ",".join(map(str, lst))
    hash_object = hashlib.md5(lst_str.encode())
    return int(hash_object.hexdigest()[:2], 16)

def decode_int_to_list(encoded_int, original_list):
    lst_str = ",".join(map(str, original_list))
    hash_object = hashlib.md5(lst_str.encode())
    if int(hash_object.hexdigest()[:2], 16) == encoded_int:
        return original_list
    else:
        return None

In [896]:
def sub_tree(path, name_tree):
    tree = Phylo.read(path, DATA_FORMAT)
    name_tree = name_tree.rsplit(".", 1)[0]
    
    
    print('='*100)
    
    tree_hash = calculate_tree_hash(tree)['terrminal_hash']
    print(f'\nTREE: HASH VALUE\n{name_tree}: {tree_hash}\n')
    
    # Lista caminhos das subárvores (que posteriormente serão utilizadas para compor a matriz de subárvores)
    dict_tree_terminals_hash = {}
    dict_aux = {}
    result_dict = {}

    for clade in tree.find_clades():
        hash_list = []
        subtree_list_termials = []
        subtree_terminals_hash = []

        subtree = Phylo.BaseTree.Tree(clade)
        name_subtree = f'{name_tree}_{clade.name}'

        if(clade.is_terminal()):
            clade_hash = calculate_tree_hash(clade.name)['terrminal_hash']
            dict_tree_terminals_hash[clade.name] = clade_hash
            
        if subtree.count_terminals() > 1:
            print(f'\nSUBTREE:\n{name_subtree}\n')
            Phylo.draw_ascii(subtree)
            print('\n')

            filepath_out = os.path.join(DATA_OUTPUT_PATH, f'{name_tree}_{clade.name}.{EXTENTION_FORMAT}')
            Phylo.write(subtree, filepath_out, DATA_FORMAT)
                           
            for subtree_clade in subtree.find_clades():
                name_terminal = subtree_clade.name
                if(subtree_clade.is_terminal()):

                    hash_result = calculate_tree_hash(name_terminal)
                    hash_list.append(hash_result)
                
                    subtree_list_termials.append(hash_result['terrminal_hash'])
                    
                    print(f'subtree clade: {subtree_clade}: {hash_result["terrminal_hash"]}')
                    print(f'Decode: {decode_tree_hash(hash_result)}')

            dict_aux[name_subtree] = {'Terminals':subtree_list_termials,'List_terminals_hash':encode_list_to_int(subtree_list_termials),'data_terminals':hash_list}
            print(f'\nTerminais: {subtree_list_termials}:{encode_list_to_int(subtree_list_termials)}\n')

    result_dict[name_tree] = dict_aux
    print(f'CLADES DA ARVORE {name_tree}:\n')       
    for key, value in dict_tree_terminals_hash.items():
        print(f'{key}: {value}') 
    print('-'*100)
 
    return result_dict

<h3 align="center"> <b>Chamada de funções</b> </h3>

<p align="center"> <b> ATENÇÃO: SE A ÁRVORE DE ENTRADA NÃO TIVER FORMATO NEXUS, MUDAR O SCHEMA EM Phylo.write( )
</b> </p>

In [897]:
# Diretório de entrada de árvores 
arquivos = os.listdir(INPUT_PATH)

# matriz com todas as subárvores
dados_brutos = []
matriz_subtree = []

for name_file in arquivos:
    if(name_file != "file.gitkeep"):
        dir_path_out_epsecif = os.path.join(DATA_OUTPUT_PATH,name_file.split(".")[0])
        file_path = os.path.join(INPUT_PATH,name_file)
        dados_brutos.append(sub_tree(file_path, name_file))

# for data in dados_brutos:
#     matriz_subtree.append(data['row_subtree'])

In [898]:
json_result = json.dumps(dados_brutos, indent=2)

with open(OUTPUT_JSON, 'w') as output_file:
    output_file.write(json_result)

In [899]:
def extract_terminais_list(data):
    all_terminais = []
    
    for _, tree_info in data.items():
        for _, subtree_info in tree_info.items():
            all_terminais.append(subtree_info['Terminals'])
                

    return all_terminais

In [900]:
for metadata in dados_brutos:
    matriz_subtree.append(extract_terminais_list(metadata))

In [901]:
print(f'\nHASH KEY ARRAY BEFORE NORMALIZING\n')

for linha in matriz_subtree:
    print(linha)

In [902]:
max_columns = max(len(row) for row in matriz_subtree)
# máximo de linhas
max_rows = len(matriz_subtree)

def preencher_matriz(matriz, valor_preenchimento):
    # Preencher as células vazias com o valor de preenchimento
    for row in matriz:
        while len(row) < max_columns:
            row.append(valor_preenchimento)

    return matriz

print(f'\nDIM: {max_rows}x{max_columns} ','-'*20)


- [FPmax - python](https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/fpmax/)

In [903]:
te = TransactionEncoder()
te_ary = te.fit(matriz_subtree).transform(matriz_subtree)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

TypeError: unhashable type: 'list'

In [ ]:
result_fpmax = fpmax(df, min_support=0.2, use_colnames=True)
# print(dict(result_fpmax))
result_fpmax

    support               itemsets
0  0.333333  (191, 35, 47, 59, 63)

In [ ]:
fpgrowth(df, min_support=0.2, use_colnames=True)

     support               itemsets
0   0.666667                   (63)
1   0.666667                   (59)
2   0.666667                   (47)
3   0.666667                   (35)
4   0.333333                  (191)
5   0.333333               (59, 63)
6   0.666667               (63, 47)
7   0.333333               (59, 47)
8   0.333333           (59, 63, 47)
9   0.666667               (59, 35)
10  0.333333               (35, 47)
11  0.333333               (35, 63)
12  0.333333           (59, 35, 47)
13  0.333333           (59, 35, 63)
14  0.333333           (35, 63, 47)
15  0.333333       (59, 35, 63, 47)
16  0.333333              (35, 191)
17  0.333333              (191, 47)
18  0.333333              (59, 191)
19  0.333333              (191, 63)
20  0.333333          (191, 35, 47)
21  0.333333          (59, 35, 191)
22  0.333333          (191, 35, 63)
23  0.333333          (191, 59, 47)
24  0.333333          (191, 63, 47)
25  0.333333          (191, 59, 63)
26  0.333333      (59, 35, 191, 47)
27  0.333333      (191, 35, 63, 47)
28  0.333333      (59, 35, 191, 63)
29  0.333333      (191, 59, 63, 47)
30  0.333333  (191, 35, 47, 59, 63)

In [ ]:
# # matriz_subtree = preencher_matriz(matriz_subtree, None)
matriz_subtree = preencher_matriz(matriz_subtree, -1)

print(f'\nHASH KEY ARRAY AFTER NORMALIZING\n')

for linha in matriz_subtree:
    print(linha)

In [ ]:
# !pip install --upgrade pandas numpy
# import warnings
# warnings.filterwarnings("ignore", category=DeprecationWarning)

In [ ]:
def find_exact_subsets(subtree_data, result_fpmax):
    subconjuntos_exatos = {}

    for key, conjunto in subtree_data.items():
        conjunto_frozen = conjunto

        for _, linha_fpmax in result_fpmax.iterrows():
            if conjunto_frozen in linha_fpmax['itemsets']:
                subconjuntos_exatos[key] = conjunto
                break
    print("\n\n\nSubárvores com subconjuntos exatos de result_fpmax:\n")
    
    for key, value in subconjuntos_exatos.items():
        print(f'{key}:{value}')

find_exact_subsets(subtree_data, result_fpmax)

/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/root/miniconda3/envs/hillai360/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1429: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

<h3 align="center"> <b> Comparação das subárvores
</b> </h3>